CREATE TABLE [dbo].[lakeflowDdlAudit_1_2](
	[SERIAL_NUMBER] [int] IDENTITY(1,1) NOT NULL,
	[CURRENT_USER] [nvarchar](128) NULL,
	[SCHEMA_NAME] [nvarchar](128) NULL,
	[TABLE_NAME] [nvarchar](128) NULL,
	[TYPE] [nvarchar](30) NULL,
	[OPERATION_TYPE] [nvarchar](30) NULL,
	[SQL_TXT] [nvarchar](2000) NULL,
	[LOGICAL_POSITION] [bigint] NOT NULL,
 CONSTRAINT [replicantDdlAuditPrimaryKey__1_2] PRIMARY KEY CLUSTERED 
(
	[SERIAL_NUMBER] ASC,
	[LOGICAL_POSITION] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
