/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF NOT EXISTS(SELECT 1 FROM [external].[ExternalSystem] WHERE CODE IN ('TESTOPENID','CPPE','NESEP','HORUS','CPPETEST','RCOPHTH','RCRADIO','EGP','NESEPV3','HORUSEP'))
BEGIN
	SET IDENTITY_INSERT [external].[ExternalSystem] OFF 
    
    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'TestOpenID', N'TESTOPENID', N'NA', N'NA', N'Example Ts and Cs for DEV...', 218, NULL, NULL, NULL, NULL, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'CPPE', N'CPPE', N'NA', N'NA', N'<p>By clicking the ''Yes'' button below, you agree to e-Learning for Healthcare  (e-LfH) and the Centre for Pharmacy Postgraduate Education (CCPE) creating a  link between your accounts on their systems so that you can log in to the  e-LfH Portal seamlessly from the CPPE site via Single Sign On. </p><p><b>Please allow 24 hours for the user account to be set up on the e-LfH system before attempting access.</b></p><p>Do you agree to e-LfH and CPPE linking your accounts?</p>', 311, 11, NULL, NULL, 403, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'NES ePortfolio', N'NESEP', N'NA', N'NA', N'<p>By clicking the ''Yes'' button below, you authorise e-Learning for Healthcare (e-LfH) to transfer all your learning history data from the e-LfH system to the NHS Education for Scotland (NES) ePortfolio system.</p><p>e-LfH and NES will take all reasonable steps to protect the privacy of your data and will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so.</p><p>Do you agree that e-LfH can transfer your learning history data to the NES ePortfolio system?</p>', NULL, NULL, NULL, NULL, NULL, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'HORUS', N'HORUS', N'NA', N'NA', N'<p>By clicking the ''Yes'' button below, you authorise e-Learning for Healthcare (e-LfH) to transfer all your learning history data from the e-LfH system to the HENW Horus ePortfolio system.</p><p>e-LfH and HENW/Horus will take all reasonable steps to protect the privacy of your data and will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so.</p><p>Do you agree that e-LfH can transfer your learning history data to the Horus ePortfolio system?</p>', NULL, NULL, NULL, NULL, NULL, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'CPPE-Test', N'CPPETEST', N'NA', N'NA', N'<p>By clicking the ''Yes'' button below, you agree to e-Learning for Healthcare  (e-LfH) and the Centre for Pharmacy Postgraduate Education (CCPE) creating a  link between your accounts on their systems so that you can log in to the  e-LfH Portal seamlessly from the CPPE site via Single Sign On. </p>  <p>Do you agree to e-LfH and CPPE linking your accounts?</p> ', 311, 11, NULL, NULL, 403, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'RCOPHTH', N'RCOPHTH', N'NA', N'NA', N'<p>By clicking the ''Yes'' button below, you agree to e-Learning for Healthcare  (e-LfH) and The Royal College of Ophthalmologists creating a  link between your accounts on their systems so that you can log in to the  e-LfH Portal seamlessly from the The Royal College of Ophthalmologists site via Single Sign On. </p>  <p>Do you agree to e-LfH and The Royal College of Ophthalmologists linking your accounts?</p> ', 218, NULL, NULL, NULL, NULL, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'RCRadiologists', N'RCRADIO', N'NA', N'NA', N'By clicking the ''Yes'' button below, you agree to e-Learning for Healthcare (e-LfH) and The Royal College of Radiologists creating a link between your accounts on their systems so that you can log in to the e-LfH Portal seamlessly from the The Royal College of Radiologists site via Single Sign On. ', NULL, NULL, NULL, NULL, NULL, NULL, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'eGP', N'EGP', N'NA', N'NA', N'By clicking the ''Yes'' button below, you authorise e-Learning for Healthcare (e-LfH) to transfer all your learning history data from the e-LfH system to the eGP ePortfolio system. e-LfH and RCGP will take all reasonable steps to protect the privacy of your data and will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. Do you agree that e-LfH can transfer your learning history data to the eGP ePortfolio system?', NULL, NULL, NULL, NULL, NULL, 0, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'NES ePortfolio v3', N'NESEPV3', N'NA', N'NA', N'<p>By clicking the ''Yes'' button below, you authorise e-Learning for Healthcare (e-LfH) to transfer all your learning history data from the e-LfH system to the NHS Education for Scotland (NES) ePortfolio system.</p><p>e-LfH and NES will take all reasonable steps to protect the privacy of your data and will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so.</p><p>Do you agree that e-LfH can transfer your learning history data to the NES ePortfolio system?</p>', NULL, NULL, NULL, NULL, NULL, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

    INSERT [external].[ExternalSystem] ([Name], [Code], [CallbackUrl], [SecretKey], [TermsAndConditions], [DefaultUserGroupId], [DefaultStaffGroupId], [DefaultJobRoleId], [DefaultGradingId], [DefaultSpecialityId], [DefaultLocationId], [Deleted], [CreateUserId], [CreateDate], [AmendUserId], [AmendDate]) VALUES (N'Horus ePortfolio', N'HORUSEP', N'NA', N'NA', N'By clicking the ''Yes'' button below, you authorise e-Learning for Healthcare (e-LfH) to transfer all your learning history data from the e-LfH system to the HEE Horus ePortfolio system. e-LfH and HEE/Horus will take all reasonable steps to protect the privacy of your data and will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. Do you agree that e-LfH can transfer your learning history data to the Horus ePortfolio system?', NULL, NULL, NULL, NULL, NULL, 1, 0, 4, SYSDATETIMEOFFSET(), 4, SYSDATETIMEOFFSET())

	SET IDENTITY_INSERT [external].[ExternalSystem] OFF
END