import { ScoObjectiveModel } from "./scoObjectiveModel";
import { ScoInteractionModel } from "./scoInteractionModel";

export class ScoModel {
	instanceId: number;
	version: string;
	children: string;
	studentId: string;
	studentName: string;
	lessonLocation: string;
	lessonStatus: string;
	lessonMode: string;
	credit: string;
	exit: string;
	entry: string;
	scoreChildren: string;
	scoreRaw: string;
	scoreMin: string;
	scoreMax: string;
	studentDataChildren: string;
	studentDataMasteryScore: string;
	studentDataMaxTimeAllowed: string;
	studentDataTimeLimitAction: string;
	studentPreferenceChildren: string;
	studentPreferenceAudio: string;
	studentPreferenceLanguage: string;
	studentPreferenceSpeed: string;
	studentPreferenceText: string;
	sessionTime: string;
	totalTime: string;
	suspendData: string;
	launchData: string;
	comments: string;
	commentsFromLms: string;
	interactionsChildren: string;
	interactionsCount: number;
	interactions: ScoInteractionModel[]; //{};
	objectivesChildren: string;
	objectivesCount: number;
	objectives: ScoObjectiveModel[]; //{};
	objectivesScoreChildren: string;

	constructor() {
		this.instanceId = 0;
		this.version = "";
		this.children = "";
		this.studentId = "";
		this.studentName = "";
		this.lessonLocation = "";
		this.lessonStatus = "ab-initio";
		this.credit = "";
		this.exit = "";
		this.entry = "";
		this.scoreChildren = "";
		this.scoreRaw = "";
		this.scoreMin = "";
		this.scoreMax = "";
		this.studentDataChildren = "";
		this.studentDataMasteryScore = "";
		this.studentDataMaxTimeAllowed = "";
		this.studentDataTimeLimitAction = "";
		this.studentPreferenceChildren = "";
		this.studentPreferenceAudio = "";
		this.studentPreferenceLanguage = "";
		this.studentPreferenceSpeed = "";
		this.studentPreferenceText = "";
		this.sessionTime = "";
		this.totalTime = "";
		this.suspendData = "";
		this.launchData = "";
		this.comments = "";
		this.commentsFromLms = "";
		this.interactionsChildren = "";
		this.interactionsCount = 0;
		this.interactions = []; //{};
		this.objectivesChildren = "";
		this.objectivesCount = 0;
		this.objectives = []; //{};
		this.objectivesScoreChildren = "";
    }
}
